#${}占位符
#可以获取之前配置的值，注意类型
#  usera:
#    namea: 1782919642@qq.com${random.int}
#    age: 112${usera.we:1}
#    list:
#    - 1
#    - 1
#    map:
#     a: 1
#     b: 2
#     c: 3
#指定文档块
#spring:
#  profiles:
#    active: prod
logging:
#  config: classpath:log/logback-spring.xml
#  path: G:/模板log/nmys
   level:
     cn.weiqiubin: trace
   pattern:
#     console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n" #配置控制台输出格式
     file: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n"
#国际化
spring:
    messages:
       basename: i18n/login
#数据源
    datasource:
       username: root
       password: wei19970707
       url: jdbc:mysql://119.29.20.227:3306/sell?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
       driver-class-name: com.mysql.jdbc.Driver
    redis:
        host: 119.29.20.227
        port: 6379
        password: wei19970707
    mail:
      username: 1782919642@qq.com
      password: etofjfwrciwkdffa
      host: smtp.qq.com
      properties:
       mail:
         smtp:
           ssl:
             enable: true
mybatis:
  mapper-locations: classpath:Mapper/UserMapper.xml
  type-aliases-package: cn.weiqiubin.domain
  configuration:
    local-cache-scope: statement
    cache-enabled: false
server:
  port: 80








---
#文档块prod
server:
  port: 8081
spring:
  profiles: prod
---
#文档块dev
server:
  port: 8082
spring:
  profiles: dev
---
#文档块test
server:
  port: 8083
spring:
  profiles: test

